import {env} from 'cloudflare:workers';
import {database,hash,iso} from '@/db/store';
import {ApiError} from './api';
import {parseFacts,derive,type FinancialFact} from './financial';
const bindings=()=>env as unknown as {DB:D1Database;ARCHIVE:R2Bucket;SEC_CONTACT_EMAIL?:string};
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
/** Shared, atomic token bucket, capacity 1 / refill 2 per second: deliberately below SEC's 10/s ceiling. */
export async function secToken(){const db=database();await db.prepare("INSERT OR IGNORE INTO sec_rate(id,tokens,updated_at) VALUES('global',1,0)").run();for(let n=0;n<80;n++){const now=Date.now();const r=await db.prepare("UPDATE sec_rate SET tokens=MIN(1,tokens+MAX(0,?-updated_at)/500.0)-1,updated_at=? WHERE id='global' AND MIN(1,tokens+MAX(0,?-updated_at)/500.0)>=1").bind(now,now,now).run();if(r.meta.changes)return;await wait(150+Math.random()*100);}throw new ApiError(429,'SEC collection is busy. Try again shortly.');}
export async function rawText(row:any){if(row.source.startsWith('sec:')){const pointer=JSON.parse(row.payload);const object=await bindings().ARCHIVE.get(pointer.objectKey);if(!object)throw new ApiError(503,'Original SEC capture unavailable');return new Response(object.body.pipeThrough(new DecompressionStream('gzip'))).text();}return row.payload;}
export async function secFetch(url:string,email:string){
 const u=new URL(url);if(!(u.origin==='https://data.sec.gov'&&/^\/(submissions|api\/xbrl\/companyfacts)\/[A-Za-z0-9.-]+(?:\.json)?$/.test(u.pathname))&&url!=='https://www.sec.gov/files/company_tickers.json')throw new ApiError(400,'SEC endpoint rejected');
 const contact=bindings().SEC_CONTACT_EMAIL||email;if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(contact))throw new ApiError(503,'A valid SEC contact email is required');
 const db=database(),source='sec:'+url;const cached=await db.prepare('SELECT * FROM source_state WHERE source=?').bind(source).first<any>();
 if(cached?.last_good_at&&Date.now()-Date.parse(cached.last_good_at)<86400000){const r=await db.prepare('SELECT * FROM raw_event WHERE id=?').bind(cached.raw_event_id).first<any>();if(r)return {raw:r,data:JSON.parse(await rawText(r))};}
 if(cached?.retry_at&&Date.parse(cached.retry_at)>Date.now())throw new ApiError(429,'SEC access is paused after a failed request. Try again later.');
 let response:Response|undefined;for(let n=0;n<3;n++){await secToken();try{response=await fetch(url,{headers:{'User-Agent':'Sentinel Research '+contact,'Accept-Encoding':'gzip, deflate',Accept:'application/json'},redirect:'manual',signal:AbortSignal.timeout(15000)});if(response.ok||response.status<500)break;}catch{if(n===2)throw new ApiError(502,'SEC could not be reached; stored data is retained.');}await wait(500*2**n);}
 if(!response?.ok){await db.prepare('INSERT INTO source_state(source,failures,retry_at,error) VALUES(?,1,?,?) ON CONFLICT(source) DO UPDATE SET failures=failures+1,retry_at=excluded.retry_at,error=excluded.error').bind(source,new Date(Date.now()+900000).toISOString(),'SEC HTTP '+response?.status).run();throw new ApiError(502,'SEC returned HTTP '+response?.status+'. Stored data is retained; requests paused for 15 minutes.');}
 const text=await response.text();if(text.length>35000000)throw new ApiError(502,'SEC response exceeded the supported capture size');const data=JSON.parse(text);const digest=await hash(text);let raw=await db.prepare('SELECT * FROM raw_event WHERE source=? AND content_hash=?').bind(source,digest).first<any>();const at=iso();
 if(!raw){const id=crypto.randomUUID(),objectKey='sec/'+digest+'.json.gz';const compressed=await new Response(new Blob([text]).stream().pipeThrough(new CompressionStream('gzip'))).arrayBuffer();await bindings().ARCHIVE.put(objectKey,compressed,{httpMetadata:{contentType:'application/gzip'}});await db.prepare('INSERT OR IGNORE INTO raw_event(id,source,fetched_at,published_at,known_from,content_hash,payload,http_status) VALUES(?,?,?,NULL,?,?,?,200)').bind(id,source,at,at,digest,JSON.stringify({objectKey,encoding:'gzip',uncompressedBytes:new TextEncoder().encode(text).length})).run();raw=await db.prepare('SELECT * FROM raw_event WHERE source=? AND content_hash=?').bind(source,digest).first<any>();}
 await db.prepare('INSERT INTO source_state(source,failures,checked_at,last_good_at,raw_event_id) VALUES(?,0,?,?,?) ON CONFLICT(source) DO UPDATE SET failures=0,checked_at=excluded.checked_at,last_good_at=excluded.last_good_at,raw_event_id=excluded.raw_event_id,retry_at=NULL,error=NULL').bind(source,at,at,raw.id).run();return {raw,data};
}
export async function resolveIdentifier(identifier:string,email:string){
 const v=identifier.trim().toUpperCase();if(/^(?:CIK)?\d{1,10}$/.test(v))return {cik:v.replace(/^CIK/,'').padStart(10,'0')};
 if(/^[A-Z]{2}[A-Z0-9]{9}\d$/.test(v))return {coverage:'none',message:'ISIN resolution is not connected. Supply the company’s SEC CIK to resolve it; no company has been guessed.'};
 const {data}=await secFetch('https://www.sec.gov/files/company_tickers.json',email);const candidates=Object.values(data).filter((e:any)=>e.ticker?.toUpperCase()===v) as any[];
 if(candidates.length>1)return {candidates:candidates.map(c=>({cik:String(c.cik_str).padStart(10,'0'),name:c.title,ticker:c.ticker})),message:'Choose the intended company by CIK.'};
 if(!candidates.length)return {coverage:'none',message:'No filing source connected for this jurisdiction or identifier. No matching SEC ticker was found; try a verified CIK.'};return {cik:String(candidates[0].cik_str).padStart(10,'0')};
}
export async function ingest(cik:string,email:string){
 if(!/^\d{10}$/.test(cik))throw new ApiError(400,'Invalid CIK');const db=database(),id='sec:'+cik,at=iso();
 try{
 const sub=await secFetch('https://data.sec.gov/submissions/CIK'+cik+'.json',email);if(String(sub.data.cik).padStart(10,'0')!==cik||!sub.data.name)throw new ApiError(502,'SEC identity response did not match the CIK');
 await db.prepare('INSERT OR IGNORE INTO entity(id,cik,name,tickers,exchanges,sic,created_at,raw_event_id) VALUES(?,?,?,?,?,?,?,?)').bind(id,cik,sub.data.name,JSON.stringify(sub.data.tickers||[]),JSON.stringify(sub.data.exchanges||[]),String(sub.data.sic||''),at,sub.raw.id).run();
 const documents=[{recent:sub.data.filings?.recent,raw:sub.raw}];
 // Submission archives are required for historical event metadata; current JSON alone is not ten years.
 const minDate=new Date(Date.now()-12*366*86400000).toISOString().slice(0,10);
 for(const f of (sub.data.filings?.files||[])){if(f.filingTo>=minDate&&/^CIK\d{10}-submissions-\d+\.json$/.test(f.name)){const h=await secFetch('https://data.sec.gov/submissions/'+f.name,email);documents.push({recent:h.data,raw:h.raw});}}
 let added=0;for(const {recent:r,raw} of documents){if(!r)continue;const ops=[];for(let i=0;i<(r.accessionNumber||[]).length;i++){const acc=r.accessionNumber[i];if(!/^\d{10}-\d{2}-\d{6}$/.test(acc)||!r.filingDate[i])continue;ops.push(db.prepare('INSERT OR IGNORE INTO filing(id,entity_id,accession,form,filed_at,known_from,period_end,items,primary_document,raw_event_id,recorded_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(acc,id,acc,r.form[i],r.filingDate[i],r.filingDate[i]+'T23:59:59.999Z',r.reportDate?.[i]||null,r.items?.[i]??null,r.primaryDocument?.[i]||null,raw.id,at));}for(let i=0;i<ops.length;i+=80){const results=await db.batch(ops.slice(i,i+80));added+=results.reduce((n,r)=>n+r.meta.changes,0);}}
 const facts=await secFetch('https://data.sec.gov/api/xbrl/companyfacts/CIK'+cik+'.json',email);if(String(facts.data.cik).padStart(10,'0')!==cik)throw new ApiError(502,'SEC facts identity mismatch');const parsed=parseFacts(facts.data,id,facts.raw.id,at);
 const ops=parsed.map(f=>db.prepare('INSERT OR IGNORE INTO financial_fact(id,entity_id,metric,source_tag,value,unit,period_start,period_end,fiscal_year,fiscal_period,form,known_from,filed,accession,raw_event_id,recorded_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(f.id,id,f.metric,f.source_tag,f.value,f.unit,f.period_start,f.period_end,f.fiscal_year,f.fiscal_period,f.form,f.known_from,f.filed,f.accession,f.raw_event_id,at));for(let i=0;i<ops.length;i+=80)await db.batch(ops.slice(i,i+80));
 // Raw data are complete before a success marker; readers ignore partial failed ingest batches.
 await db.prepare('INSERT INTO sec_run(id,entity_id,known_from,status,message,raw_event_id) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),id,iso(),'success',`${parsed.length} supported observations processed; ${added} new filing records.`,facts.raw.id).run();
 const all=(await db.prepare('SELECT * FROM financial_fact WHERE entity_id=?').bind(id).all<FinancialFact>()).results;
 const derived=derive(all,iso());const cache=[];for(const f of derived){const key=await hash(JSON.stringify([id,f.metric,f.period_end,f.method,f.inputs.map(x=>x.id)]));cache.push(db.prepare('INSERT OR IGNORE INTO derived_metric(id,entity_id,metric,value,unit,period_end,known_from,recorded_at,inputs_json,method,confidence,reason) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(key,id,f.metric,f.value,f.unit,f.period_end,f.known_from||at,iso(),JSON.stringify(f.inputs.map(x=>x.id)),f.method,f.confidence,f.reason));}for(let i=0;i<cache.length;i+=80)await db.batch(cache.slice(i,i+80));
 return {entity_id:id,newFilings:added,observations:parsed.length};
 }catch(e){await db.prepare('INSERT INTO sec_run(id,entity_id,known_from,status,message) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),id,iso(),'failed',e instanceof Error?e.message:'Ingest failed').run();throw e;}
}
export async function companyFile(entityId:string,asOf:string,mode='public',owner=''){
 const db=database(),entity=await db.prepare('SELECT * FROM entity WHERE id=?').bind(entityId).first<any>();if(!entity)throw new ApiError(404,'Company not found');
 const runs=(await db.prepare('SELECT * FROM sec_run WHERE entity_id=? ORDER BY known_from DESC LIMIT 10').bind(entityId).all()).results;const lastGood=runs.find(r=>r.status==='success');
 const records=(await db.prepare("SELECT f.* FROM financial_fact f WHERE entity_id=? AND EXISTS(SELECT 1 FROM sec_run s WHERE s.entity_id=f.entity_id AND s.status='success' AND s.raw_event_id=f.raw_event_id AND (?='public' OR s.known_from<=?))").bind(entityId,mode,asOf).all<FinancialFact>()).results;
 const figures=derive(records,asOf,mode==='recorded'?asOf:undefined);const filings=(await db.prepare("SELECT * FROM filing WHERE entity_id=? AND known_from<=? AND (?='public' OR recorded_at<=?) ORDER BY known_from DESC,accession DESC").bind(entityId,asOf,mode,asOf).all()).results;
 const estimates=(await db.prepare('SELECT * FROM maintenance_estimate WHERE entity_id=? AND owner=? AND known_from<=? ORDER BY known_from DESC').bind(entityId,owner,asOf).all()).results;
 for(const f of figures.filter(f=>f.metric==='maintenance_capex')){const e=estimates.find(e=>e.period_end===f.period_end);if(e){f.value=Number(e.value);f.confidence='estimated';f.method=String(e.method);f.known_from=String(e.known_from);f.reason='Human estimate; separate owner-earnings reconciliation still required';}}
 return {entity,figures,filings,estimates,asOf,mode,lastGoodAt:lastGood?.known_from||null,stale:!lastGood||Date.now()-Date.parse(String(lastGood.known_from))>86400000||runs[0]?.status==='failed',runs,notice:mode==='recorded'?'Only data captured by Sentinel by the cutoff.':'Reconstructed public filing history, captured later. Filed dates have day precision: values become eligible at the end of that UTC date. Not a record of what Sentinel held then.',coverage:records.length?'us-gaap-supported-tags':'No supported USD US-GAAP facts; IFRS and custom tags are unavailable.'};
}
