import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {Miniflare,createFetchMock}=require(require.resolve('miniflare',{paths:[require.resolve('wrangler/package.json')]}));
const esbuild=require(require.resolve('esbuild',{paths:[require.resolve('wrangler/package.json')]}));
const worker=`import * as watch from './app/api/watchlist/route';import * as company from './app/api/company/route';import * as criteria from './app/api/criteria/route';import * as journal from './app/api/journal/route';import * as market from './app/api/market/route';import * as refresh from './app/api/refresh/route';import {evaluate} from './lib/sentinel/criteria';import {parseFacts,derive,selectFacts} from './lib/sentinel/financial';export default {async fetch(request,env){globalThis.testUser=request.headers.get('x-test-user');const p=new URL(request.url).pathname;if(p==='/pure'){const x=await request.json();return Response.json(evaluate(x.predicate,x.figures,x.filings,x.asOf))}const routes={'/watch':watch,'/company':company,'/criteria':criteria,'/journal':journal,'/market':market,'/refresh':refresh};return routes[p][request.method](request)}};`;
const built=await esbuild.build({stdin:{contents:worker,resolveDir:process.cwd(),loader:'ts'},bundle:true,write:false,platform:'neutral',format:'esm',target:'es2022',external:['cloudflare:workers'],plugins:[{name:'identity',setup(b){b.onResolve({filter:/chatgpt-auth$/},()=>({path:'identity',namespace:'identity'}));b.onLoad({filter:/.*/,namespace:'identity'},()=>({contents:'export async function getChatGPTUser(){return globalThis.testUser?{userId:globalThis.testUser,email:"research@example.test"}:null}',loader:'js'}))}}]});
const mock=createFetchMock();mock.disableNetConnect();const options={modules:true,compatibilityDate:'2026-05-15',cf:false,d1Databases:['DB'],r2Buckets:['ARCHIVE'],fetchMock:mock,script:built.outputFiles[0].text,bindings:{SENTINEL_FORCE_FAIL:'coinbase:BTC'}};const mf=new Miniflare(options);let db=await mf.getD1Database('DB');
for(const file of readdirSync('drizzle').filter(s=>s.endsWith('.sql')).sort())for(const sql of readFileSync('drizzle/'+file,'utf8').split('--> statement-breakpoint').filter(s=>s.trim()))await db.prepare(sql).run();
async function req(path,method='GET',data,user='owner-a'){const r=await mf.dispatchFetch('http://localhost'+path,{method,headers:{'x-test-user':user,Origin:'http://localhost','Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});return {status:r.status,data:await r.json()};}
const facts=(cik)=>{const tags={Revenues:100,OperatingIncomeLoss:20,NetIncomeLoss:10,NetCashProvidedByUsedInOperatingActivities:5,PaymentsToAcquirePropertyPlantAndEquipment:3,CashAndCashEquivalentsAtCarryingValue:10,LongTermDebtNoncurrent:20,LongTermDebtCurrent:5,StockholdersEquity:50,IncomeTaxExpenseBenefit:5,IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest:25,WeightedAverageNumberOfDilutedSharesOutstanding:100,CostOfRevenue:60,DepreciationDepletionAndAmortization:2};const us={};for(const [tag,val] of Object.entries(tags)){const unit=tag.includes('Shares')?'shares':'USD';us[tag]={units:{[unit]:Array.from({length:10},(_,i)=>{const year=2014+i;return {start:['CashAndCashEquivalentsAtCarryingValue','LongTermDebtNoncurrent','LongTermDebtCurrent','StockholdersEquity'].includes(tag)?undefined:year+'-01-01',end:year+'-12-31',val:tag==='NetCashProvidedByUsedInOperatingActivities'&&year<2022?8:val,accn:cik+'-'+String(year+1).slice(2)+'-000001',fy:year+1,fp:'FY',form:'10-K',filed:(year+1)+'-11-01'}})}};}us.Revenues.units.USD.push({...us.Revenues.units.USD.at(-1),val:120,accn:cik+'-25-000002',filed:'2025-03-01'});us.NetCashProvidedByUsedInOperatingActivities.units.USD.push({...us.NetCashProvidedByUsedInOperatingActivities.units.USD.at(-1),val:10,accn:cik+'-25-000002',filed:'2025-03-01'});return {cik:Number(cik),facts:{'us-gaap':us}};};
const stamps=[];function sec(cik){const data=facts(cik);const rows=[...data.facts['us-gaap'].Revenues.units.USD];const recent={accessionNumber:rows.map(r=>r.accn),filingDate:rows.map(r=>r.filed),form:rows.map(r=>r.form),reportDate:rows.map(r=>r.end),items:rows.map(()=>''),primaryDocument:rows.map(()=>'report.htm')};for(const [path,payload] of [['/submissions/CIK'+cik+'.json',{cik:Number(cik),name:'Fixture company '+cik,tickers:['FIX'],exchanges:['Test'],filings:{recent,files:[]}}],['/api/xbrl/companyfacts/CIK'+cik+'.json',data]])mock.get('https://data.sec.gov').intercept({path,headers:{'user-agent':'Sentinel Research research@example.test'}}).reply(()=>{stamps.push(Date.now());return {statusCode:200,data:JSON.stringify(payload)}});}
try{
await test('durable market reads never contact unreachable upstream; forced failure preserves value and logs incident',async()=>{
 const old=new Date(Date.now()-300000).toISOString(),id=crypto.randomUUID();await db.prepare('INSERT INTO raw_event(id,source,fetched_at,known_from,content_hash,payload,http_status) VALUES(?,?,?,?,?,?,200)').bind(id,'coinbase:BTC',old,old,'fixture',JSON.stringify({data:{base:'BTC',currency:'USD',amount:'123.45'}})).run();await db.prepare('INSERT INTO source_state(source,failures,last_good_at,raw_event_id) VALUES(?,0,?,?)').bind('coinbase:BTC',old,id).run();
 assert.equal((await req('/market')).status,200);
 for(let i=0;i<3;i++){await db.prepare("UPDATE source_state SET checked_at=NULL,retry_at=NULL WHERE source='coinbase:BTC'").run();const r=await req('/refresh','POST',{kind:'market'});assert.equal(r.status,200);const q=r.data.quotes.find(q=>q.symbol==='BTC');assert.equal(q.amount,123.45);assert.equal(q.stale,true);const s=r.data.sources.find(s=>s.name.includes('BTC'));assert.equal(s.failures,i+1);assert.ok(s.retryAt);assert.equal(s.lastGoodAt,old);}
 assert.equal((await db.prepare("SELECT COUNT(*) n FROM signal_log WHERE entity='coinbase:BTC' AND kind='feed_health'").first()).n,1);
 const decision={requestId:crypto.randomUUID(),kind:'decision',entity:'Sentinel forced-failure test',statement:'Local forced-failure test retained BTC 123.45 and its original timestamp across three failing collection runs. The operational incident was appended.',counterEvidence:'Browser rendering and a one-hour production observation have not been verified by this test.',references:'tests/work-order03.test.mjs; isolated Miniflare fixtures, not market data',disposition:'research',probability:null,resolvesAt:null,resolutionRule:''};assert.equal((await req('/journal','POST',decision)).status,200);
});
await test('append-only resolution corrections preserve original prediction and historical outcomes',async()=>{
 const id=crypto.randomUUID(),past='2020-01-01T00:00:00.000Z',original=JSON.stringify({statement:'Fixture original prediction',resolutionRule:'Binary fixture'});await db.prepare('INSERT INTO signal_log(id,owner,created_at,kind,body,probability,resolves_at) VALUES(?,?,?,?,?,?,?)').bind(id,'owner-a',past,'prediction',original,.7,past).run();const first={kind:'resolution',requestId:crypto.randomUUID(),resolves_id:id,outcome:1,evidence:'The independently dated fixture confirms the outcome.',resolution_source_url:'https://example.com/evidence'};assert.equal((await req('/journal','POST',first)).status,200);const cutoff=new Date().toISOString();await new Promise(r=>setTimeout(r,10));const next={...first,requestId:crypto.randomUUID(),outcome:0,supersedes_id:first.requestId};assert.equal((await req('/journal','POST',next)).status,200);assert.equal((await req('/journal','POST',{...next,requestId:crypto.randomUUID()})).status,409);const j=(await req('/journal')).data.entries.find(e=>e.id===id);assert.equal(j.resolutionHistory.length,2);assert.equal(j.outcome,0);assert.ok(Math.abs((j.probability-j.outcome)**2-.49)<1e-9);assert.equal((await req('/journal?asOf='+cutoff)).data.entries.find(e=>e.id===id).outcome,1);assert.equal((await db.prepare('SELECT body FROM signal_log WHERE id=?').bind(id).first()).body,original);
});
await test('three fixture companies ingest ten annual years, raw gzip capture, idempotency and shared rate limit',async()=>{
 for(const cik of ['0000000001','0000000002','0000000003']){sec(cik);const r=await req('/watch','POST',{identifier:cik});assert.equal(r.status,200,JSON.stringify(r));}
 for(let i=1;i<stamps.length;i++)assert.ok(stamps[i]-stamps[i-1]>=480);
 const before=(await db.prepare('SELECT COUNT(*) n FROM financial_fact').first()).n;assert.equal((await req('/watch','POST',{identifier:'0000000001'})).status,200);assert.equal((await db.prepare('SELECT COUNT(*) n FROM financial_fact').first()).n,before);
 const file=(await req('/company?entity=sec:0000000001')).data;assert.equal(file.figures.filter(f=>f.metric==='revenue').length,10);assert.equal(file.figures.find(f=>f.metric==='owner_earnings').value,null);assert.equal(file.figures.filter(f=>f.metric==='revenue').every(f=>f.inputs.every(i=>i.source_tag&&i.accession&&i.filed)),true);const bucket=await mf.getR2Bucket('ARCHIVE');assert.ok((await bucket.list()).objects.length>=6);
});
await test('public and recorded clocks, filing-date look-ahead, and restatements are independent',async()=>{
 const early=(await req('/company?entity=sec:0000000001&asOf=2024-06-01T00:00:00.000Z')).data;assert.equal(early.figures.find(f=>f.metric==='revenue'&&f.period_end==='2023-12-31'),undefined);
 const middle=(await req('/company?entity=sec:0000000001&asOf=2025-01-01T00:00:00.000Z')).data;assert.equal(middle.figures.find(f=>f.metric==='revenue'&&f.period_end==='2023-12-31').value,100);
 const later=(await req('/company?entity=sec:0000000001&asOf=2025-04-01T00:00:00.000Z')).data;assert.equal(later.figures.find(f=>f.metric==='revenue'&&f.period_end==='2023-12-31').value,120);
 const recorded=(await req('/company?entity=sec:0000000001&mode=recorded&asOf=2025-04-01T00:00:00.000Z')).data;assert.equal(recorded.figures.length,0);
});
let memoId,criterionId;
await test('criterion trips at the exact eligible filing, replay matches; later restatement appends pass',async()=>{
 memoId=crypto.randomUUID();assert.equal((await req('/criteria','POST',{action:'memo',requestId:memoId,entity_id:'sec:0000000001',thesis:'Fixture thesis: annual operating cash flow remains at least seventy percent of net income.',position_open:true})).status,200);
 criterionId=crypto.randomUUID();const create={action:'criterion',requestId:criterionId,memo_id:memoId,predicate:{all:[{metric:'cash_conversion',op:'<',value:.7,consecutive_periods:2}]}};assert.equal((await req('/criteria','POST',create)).status,200);
 const before=await req('/criteria','POST',{action:'evaluate',criterion_id:criterionId,as_of:'2024-06-01T00:00:00.000Z'});assert.equal(before.data.result,'pass');const at='2024-11-01T23:59:59.999Z';const r=await req('/criteria','POST',{action:'evaluate',criterion_id:criterionId,as_of:at});assert.equal(r.data.result,'trip');assert.equal(r.data.triggeringFiling.accession,'0000000001-24-000001');const replay=await req('/criteria','POST',{action:'evaluate',criterion_id:criterionId,as_of:at});assert.deepEqual(replay.data.checks,r.data.checks);
 const after=await req('/criteria','POST',{action:'evaluate',criterion_id:criterionId,as_of:'2025-03-01T23:59:59.999Z'});assert.equal(after.data.result,'pass');const rows=(await req('/criteria')).data.evaluations;assert.ok(rows.find(e=>e.id===after.data.id).supersedes_id);assert.ok(rows.find(e=>e.id===r.data.id));
 assert.equal((await req('/criteria','POST',{...create,requestId:crypto.randomUUID(),supersedes_id:criterionId})).status,400);
});
await test('missing input is unknown on both runs, creates operational alert, never passes',async()=>{
 const id=crypto.randomUUID();const r=await req('/criteria','POST',{action:'criterion',requestId:id,memo_id:memoId,predicate:{any:[{metric:'unsupported',op:'>',value:1}]}});assert.equal(r.data.evaluation.result,'unknown');assert.equal((await req('/criteria','POST',{action:'evaluate',criterion_id:id})).data.result,'unknown');assert.ok((await req('/criteria')).data.alerts.some(a=>a.tier==='Operational'));
});
await test('one breach cannot satisfy a two-period streak; a missing annual period is unknown',async()=>{
 const fig=(end,val)=>({metric:'cash_conversion',value:val,unit:'ratio',period_end:end,known_from:'2024-01-01T00:00:00.000Z',inputs:[],confidence:'computed',reason:'fixture'});const run=figures=>req('/pure','POST',{predicate:{all:[{metric:'cash_conversion',op:'<',value:.7,consecutive_periods:2}]},figures,filings:[],asOf:'2025-01-01T00:00:00.000Z'});
 assert.equal((await run([fig('2023-12-31',.5),fig('2022-12-31',.8)])).data.result,'pass');assert.equal((await run([fig('2023-12-31',.5),fig('2022-12-31',.5)])).data.result,'trip');assert.equal((await run([fig('2023-12-31',.5),fig('2021-12-31',.5)])).data.result,'unknown');
});
await test('clearing the server failure flag recovers within the next requested collection',async()=>{
 await mf.setOptions({...options,bindings:{SENTINEL_FORCE_FAIL:''}});db=await mf.getD1Database('DB');
 mock.get('https://api.coinbase.com').intercept({path:'/v2/prices/BTC-USD/spot'}).reply(200,JSON.stringify({data:{base:'BTC',currency:'USD',amount:'124'}}));
 const r=await req('/refresh','POST',{kind:'market'});assert.equal(r.status,200);const q=r.data.quotes.find(q=>q.symbol==='BTC');assert.equal(q.amount,124);assert.equal(q.stale,false);assert.equal(r.data.sources.find(s=>s.name.includes('BTC')).failures,0);
});
await test('database blocks mutations to captured facts, predictions, resolutions, criteria and evaluations',async()=>{
 for(const table of ['raw_event','financial_fact','signal_log','resolution_record','kill_criterion','criterion_evaluation'])for(const operation of [`DELETE FROM ${table}`,`UPDATE ${table} SET id=id`])await assert.rejects(()=>db.prepare(operation).run(),/immutable/);
 assert.equal((await req('/criteria','GET',undefined,'owner-b')).data.memos.length,0);
});
}finally{await mf.dispose();}
