import {identity,body,json,failure,ApiError} from '@/lib/sentinel/api';
import {database,iso} from '@/db/store';
import {appendCriterion,evaluateCriterion} from '@/lib/sentinel/criteria';
import {z} from 'zod';
export async function GET(request:Request){try{const owner=await identity(),p=new URL(request.url).searchParams,cutoff=p.get('recordedAsOf')||iso();if(!Number.isFinite(Date.parse(cutoff)))throw new ApiError(400,'Invalid recorded cutoff');const at=new Date(cutoff).toISOString();const db=database();const memos=(await db.prepare('SELECT m.*,e.name FROM research_memo m JOIN entity e ON e.id=m.entity_id WHERE m.owner=? AND m.known_from<=? ORDER BY m.known_from DESC').bind(owner,at).all()).results;const criteria=(await db.prepare('SELECT c.* FROM kill_criterion c JOIN research_memo m ON m.id=c.memo_id WHERE m.owner=? AND c.known_from<=? ORDER BY c.known_from DESC').bind(owner,at).all()).results;const evaluations=(await db.prepare('SELECT v.* FROM criterion_evaluation v JOIN kill_criterion c ON c.id=v.kill_criterion_id JOIN research_memo m ON m.id=c.memo_id WHERE m.owner=? AND v.evaluated_at<=? ORDER BY v.evaluated_at DESC,v.id DESC LIMIT 500').bind(owner,at).all()).results;const alerts=(await db.prepare('SELECT * FROM criterion_alert WHERE owner=? AND known_from<=? ORDER BY known_from DESC LIMIT 100').bind(owner,at).all()).results;return json({memos,criteria,evaluations,alerts});}catch(e){return failure(e)}}
export async function POST(request:Request){try{const owner=await identity(request),d=await body(request),db=database();
 if(d.action==='memo'){const p=z.object({action:z.literal('memo'),requestId:z.string().uuid(),entity_id:z.string().max(40),thesis:z.string().trim().min(30).max(12000),position_open:z.boolean()}).strict().safeParse(d);if(!p.success)throw new ApiError(400,'Choose a company and provide a specific thesis (30+ characters)');const v=p.data;if(!await db.prepare('SELECT id FROM entity WHERE id=?').bind(v.entity_id).first())throw new ApiError(404,'Company not found');await db.prepare('INSERT OR IGNORE INTO research_memo(id,owner,entity_id,thesis,position_open,known_from) VALUES(?,?,?,?,?,?)').bind(v.requestId,owner,v.entity_id,v.thesis,v.position_open?1:0,iso()).run();return json({id:v.requestId});}
 if(d.action==='criterion'){const {action,...input}=d;return json(await appendCriterion(owner,input));}
 if(d.action==='evaluate'){const at=d.as_of||iso();if(!Number.isFinite(Date.parse(at))||Date.parse(at)>Date.now())throw new ApiError(400,'Choose a valid past time');const c=await db.prepare('SELECT c.*,m.owner,m.entity_id,m.thesis FROM kill_criterion c JOIN research_memo m ON m.id=c.memo_id WHERE c.id=? AND m.owner=?').bind(d.criterion_id,owner).first();if(!c)throw new ApiError(404,'Criterion not found');return json(await evaluateCriterion(c,c,new Date(at).toISOString()));}throw new ApiError(400,'Unknown action');}catch(e){return failure(e)}}
