'use client';
import {newId} from '@/lib/sentinel/client-id';
import {useEffect,useState,useRef} from 'react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
const when=(s:string)=>s?new Date(s).toLocaleString():'Unknown';
const num=(v:number|null)=>v===null?'Unavailable':new Intl.NumberFormat('en-US',{maximumFractionDigits:4}).format(v);
async function api(url:string,data?:unknown){const r=await fetch(url,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{cache:'no-store'});let j:any;try{j=await r.json()}catch{throw new Error('The server did not return a usable response. Saved records remain available; try again.')}if(!r.ok)throw new Error(j.error||'Request unavailable');return j;}
function Choice({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:[string,string][];label:string}){return <label>{label}<Select value={value} onValueChange={onChange}><SelectTrigger className="w-full"><SelectValue placeholder="Choose…"/></SelectTrigger><SelectContent>{items.map(([id,name])=><SelectItem key={id} value={id}>{name}</SelectItem>)}</SelectContent></Select></label>}
export function CompanyResearch(){
 const [entities,setEntities]=useState<any[]>([]),[identifier,setIdentifier]=useState(''),[selected,setSelected]=useState(''),[data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[at,setAt]=useState(''),[mode,setMode]=useState('public'),[metric,setMetric]=useState('revenue'),[candidates,setCandidates]=useState<any[]>([]),[estimate,setEstimate]=useState(''),[estimatePeriod,setEstimatePeriod]=useState(''),[method,setMethod]=useState('');
 async function list(){const j=await api('/api/watchlist');setEntities(j.entities);return j.entities;}
 useEffect(()=>{list().catch(e=>setError(e.message))},[]);
 async function load(id=selected){if(!id)return;setBusy(true);setError('');try{setData(await api('/api/company?entity='+encodeURIComponent(id)+'&mode='+mode+(at?'&asOf='+encodeURIComponent(new Date(at).toISOString()):'')));setSelected(id)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function add(id=identifier){setBusy(true);setError('');setCandidates([]);try{const j=await api('/api/watchlist',{identifier:id});if(!j.entity_id){setError(j.message);setCandidates(j.candidates||[]);return;}await list();setSelected(j.entity_id);setData(await api('/api/company?entity='+encodeURIComponent(j.entity_id)));setAt('');setMode('public');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const figures=(data?.figures||[]).filter((f:any)=>f.metric===metric).sort((a:any,b:any)=>b.period_end.localeCompare(a.period_end)).slice(0,10);const metrics=['revenue','operating_income','cfo','capex','net_debt','shares_diluted','effective_tax_rate','nopat','invested_capital','roic','incremental_roic_3y','incremental_roic_4y','incremental_roic_5y','cash_conversion','gross_margin','share_count_yoy','net_debt_to_ebitda','maintenance_capex','owner_earnings'];
 return <section><div className="section-heading"><div><h2>Company files</h2><p>Annual financial evidence, filing history and the assumptions behind each calculation.</p></div></div><div className="record-panel"><form className="entity-form" onSubmit={e=>{e.preventDefault();void add()}}><label>SEC ticker or CIK<input required maxLength={80} value={identifier} onChange={e=>setIdentifier(e.target.value)} placeholder="AAPL, MSFT, LMT or a verified CIK"/></label><button className="primary-button" disabled={busy}>{busy?'Reading filings…':'Add / refresh company'}</button></form><p className="feed-footnote">SEC requests identify Sentinel using your signed-in account email. Responses are cached for 24 hours. Refresh is manual; nothing runs while the app is closed. ISIN mapping, IFRS and non-SEC filing sources are not connected.</p>{candidates.map(c=><button key={c.cik} className="outline-button" disabled={busy} onClick={()=>void add(c.cik)}>{c.name} · {c.cik}</button>)}</div>
 {error&&<div className="feed-warning" role="alert">{error}</div>}
 {entities.length>0&&<div className="entity-form record-panel"><Choice label="Saved company" value={selected} onChange={id=>void load(id)} items={entities.map(e=>[e.id,e.name])}/><Choice label="History basis" value={mode} onChange={setMode} items={[["public","Public filing history (reconstructed)"],["recorded","What Sentinel had captured"]]}/><label>As of (local time)<input type="datetime-local" value={at} onChange={e=>setAt(e.target.value)}/></label><button className="outline-button" disabled={busy||!selected} onClick={()=>void load()}>Apply cutoff</button></div>}
 {data&&<><div className="section-heading"><div><h3>{data.entity.name}</h3><p>CIK {data.entity.cik} · {JSON.parse(data.entity.tickers).join(', ')} · {JSON.parse(data.entity.exchanges).join(', ')}</p></div><span className={data.stale?'badge amber-text':'badge'}>{data.stale?'STALE / NO SUCCESSFUL CAPTURE':'Stored capture available'}</span></div><p className="feed-warning">{data.notice}</p><p className="feed-footnote">Last successful ingest: {when(data.lastGoodAt)} · Coverage: {data.coverage}. Source dates have day precision; exact publication times are unavailable. Annual periods only; quarterly/YTD amounts are not substituted.</p><div className="record-panel"><Choice label="Financial measure" value={metric} onChange={setMetric} items={metrics.map(m=>[m,m.replaceAll('_',' ')])}/><p className="feed-footnote">Most recent {figures.length} annual periods available at this cutoff (up to 10). Missing years are not filled. ROIC uses an estimated operating-cash reserve of 2% of revenue. EBITDA is an operating-income + depreciation proxy.</p><div className="financial-table"><Table><TableHeader><TableRow><TableHead>Period end</TableHead><TableHead>Value / unit</TableHead><TableHead>Evidence</TableHead></TableRow></TableHeader><TableBody>{figures.map((f:any)=><TableRow key={f.period_end}><TableCell>{f.period_end}</TableCell><TableCell className={f.value===null?'amber-text':''}>{num(f.value)} {f.value===null?'':f.unit}<br/><small>{f.confidence}</small></TableCell><TableCell><p>{f.reason}</p><details><summary>Method and source records ({f.inputs.length})</summary><p>{f.method} · Publicly known by {when(f.known_from)}</p>{f.inputs.map((i:any)=><div className="source-fact" key={i.id}><strong>{i.metric}: {num(i.value)} {i.unit}</strong><p>Tag: {i.source_tag}<br/>{i.form} · {i.accession} · Filed {i.filed}<br/>Period: {i.period_start||'Instant'} → {i.period_end}<br/>Captured {when(i.recorded_at)}</p><a href={'https://www.sec.gov/Archives/edgar/data/'+Number(data.entity.cik)+'/'+i.accession.replaceAll('-','')+'/'+i.accession+'-index.html'} target="_blank" rel="noreferrer">SEC filing</a> · <a href={'/api/history?raw='+encodeURIComponent(i.raw_event_id)} target="_blank" rel="noreferrer">Original capture and SHA-256</a></div>)}</details></TableCell></TableRow>)}</TableBody></Table></div>{!figures.length&&<div className="feed-warning">Not yet known or unavailable at this cutoff. No value has been substituted.</div>}</div>
 {metric==='maintenance_capex'&&<form className="record-panel" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api('/api/company',{requestId:newId(),entity_id:selected,period_end:estimatePeriod,value:Number(estimate),method});setEstimate('');setMethod('');await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><h3>Append a human estimate</h3><div className="entity-form"><label>Annual period end<input required type="date" value={estimatePeriod} onChange={e=>setEstimatePeriod(e.target.value)}/></label><label>Maintenance capex (USD)<input required min="0" type="number" value={estimate} onChange={e=>setEstimate(e.target.value)}/></label></div><label>Triangulation method and evidence<textarea required minLength={30} value={method} onChange={e=>setMethod(e.target.value)}/></label><p>Owner earnings remains unavailable until a complete reconciliation is supplied; this estimate alone is not sufficient.</p><button className="primary-button" disabled={busy}>Record estimate permanently</button></form>}
 <details className="record-panel"><summary>Filing metadata ({data.filings.length})</summary>{data.filings.slice(0,100).map((f:any)=><p key={f.id}>{f.form} · {f.accession} · Filed {f.filed_at} · Items {f.items||'unavailable'} · Captured {when(f.recorded_at)}</p>)}{data.filings.length>100&&<p>First 100 shown. Evaluations use all stored metadata eligible at the cutoff.</p>}</details></>}
 {!entities.length&&!busy&&<div className="empty"><h3>Add your first company file</h3><p>Resolve an SEC ticker or CIK to a stable company identity. Missing filings and unsupported jurisdictions stay visible.</p></div>}
 </section>;
}
export function ThesisChecks({alertsOnly=false}:{alertsOnly?:boolean}){
 const pending=useRef<{fingerprint:string;id:string}|null>(null);
 const [data,setData]=useState<any>(null),[entities,setEntities]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[entity,setEntity]=useState(''),[thesis,setThesis]=useState(''),[position,setPosition]=useState(false),[memo,setMemo]=useState(''),[predicate,setPredicate]=useState('{"all":[{"metric":"cash_conversion","op":"<","value":0.7,"consecutive_periods":2}]}'),[supersedes,setSupersedes]=useState<string|null>(null),[reason,setReason]=useState(''),[asOf,setAsOf]=useState(''),[recorded,setRecorded]=useState('');
 async function load(){try{const j=await api('/api/criteria'+(recorded?'?recordedAsOf='+encodeURIComponent(new Date(recorded).toISOString()):''));setData(j);if(!alertsOnly)setEntities((await api('/api/watchlist')).entities)}catch(e){setError((e as Error).message)}}
 useEffect(()=>{void load()},[]);
 async function write(payload:any){setBusy(true);setError('');try{if(payload.requestId){const {requestId,...content}=payload;const fingerprint=JSON.stringify(content);if(pending.current?.fingerprint!==fingerprint)pending.current={fingerprint,id:requestId};payload={...payload,requestId:pending.current.id};}await api('/api/criteria',payload);pending.current=null;await load();return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false)}}
 const active=(data?.criteria||[]).filter((c:any)=>!data.criteria.some((n:any)=>n.supersedes_id===c.id));const latest=(id:string)=>data?.evaluations.filter((e:any)=>e.kill_criterion_id===id).sort((a:any,b:any)=>b.as_of.localeCompare(a.as_of)||b.evaluated_at.localeCompare(a.evaluated_at))[0];const unknown=active.filter((c:any)=>!latest(c.id)||latest(c.id).result==='unknown').length;
 return <section>{!alertsOnly&&<><div className="section-heading"><div><h2>Thesis checks</h2><p>Define what would invalidate your reasoning. Checks run after manual filing refreshes or when you evaluate them here.</p></div></div><div className="feed-warning">{data?`${unknown} of ${active.length} kill criteria cannot currently be evaluated.`:'Status unknown — criterion records have not loaded.'} Unknown is not passing. Period streaks use consecutive annual fiscal periods; gaps break the streak.</div><form className="record-panel" onSubmit={async e=>{e.preventDefault();if(await write({action:'memo',requestId:newId(),entity_id:entity,thesis,position_open:position}))setThesis('')}}><h3>Record a thesis memo</h3><Choice label="Company" value={entity} onChange={setEntity} items={entities.map(e=>[e.id,e.name])}/><label>Your thesis and the business assumptions it relies on<textarea required minLength={30} value={thesis} onChange={e=>setThesis(e.target.value)}/></label><label className="inline-choice"><Checkbox checked={position} onCheckedChange={v=>setPosition(v===true)}/> I currently hold a position (user-declared)</label><button className="primary-button" disabled={busy||!entity}>Record memo permanently</button></form>
 <form className="record-panel" onSubmit={async e=>{e.preventDefault();let parsed;try{parsed=JSON.parse(predicate)}catch{setError('Condition must be valid JSON.');return}if(await write({action:'criterion',requestId:newId(),memo_id:memo,predicate:parsed,supersedes_id:supersedes,supersede_reason:reason})){setSupersedes(null);setReason('')}}}><h3>{supersedes?'Append a justified criterion change':'Define a kill criterion'}</h3><Choice label="Memo" value={memo} onChange={v=>{setMemo(v);setSupersedes(null)}} items={(data?.memos||[]).map((m:any)=>[m.id,m.name+' · '+when(m.known_from)])}/><label>Condition (all / any group)<textarea className="predicate-editor" required value={predicate} onChange={e=>setPredicate(e.target.value)}/></label><details><summary>Condition format and supported checks</summary><p>Use one “all” or “any” group. Comparisons: &gt;, &gt;=, &lt;, &lt;=, ==, !=. Ratios use decimal units (0.34 = 34%). Consecutive periods default to one annual period.</p><p>Metrics: cash_conversion, net_debt_to_ebitda, gross_margin, share_count_yoy, roic, revenue, operating_income, cfo, capex, net_debt. Other unsupported names return unknown.</p><p>Events: {JSON.stringify({event:'auditor_change'})}, late_filing, material_weakness_disclosed. Events search captured metadata through the cutoff. Absence is unknown; material weakness needs evidence beyond item codes.</p><p>A group with any unknown input stays unknown, even if another child is passing. This conservative rule prevents an incomplete check looking clear.</p></details>{supersedes&&<label>Required dated justification<textarea required minLength={10} value={reason} onChange={e=>setReason(e.target.value)}/></label>}<button className="primary-button" disabled={busy||!memo}>Record and evaluate</button>{supersedes&&<button type="button" className="text-button" onClick={()=>setSupersedes(null)}>Cancel change</button>}</form>
 <div className="entity-form record-panel"><label>Evaluation as of (public history, local time)<input type="datetime-local" value={asOf} onChange={e=>setAsOf(e.target.value)}/></label><label>View record history as of (local time)<input type="datetime-local" value={recorded} onChange={e=>setRecorded(e.target.value)}/></label><button className="outline-button" onClick={()=>void load()}>Apply record cutoff / refresh</button></div>
 {(data?.memos||[]).map((m:any)=><article className="record-panel" key={m.id}><h3>{m.name}</h3><p className="preserve-text">{m.thesis}</p><p className="feed-footnote">Recorded {when(m.known_from)} · Position {m.position_open?'open':'not declared'} at memo creation</p>{active.filter((c:any)=>c.memo_id===m.id).map((c:any)=>{const e=latest(c.id);return <div className={'criterion-card '+(e?.result||'unknown')} key={c.id}><strong>{e?.result?.toUpperCase()||'UNKNOWN — not evaluated'}</strong><pre>{c.predicate_json}</pre><p className="preserve-text">{e?.reason||'No evaluation recorded.'}</p><p className="feed-footnote">Recorded {when(c.known_from)} · Last checked {when(e?.evaluated_at)} · Public cutoff {when(e?.as_of)}</p><button className="outline-button" disabled={busy} onClick={()=>void write({action:'evaluate',criterion_id:c.id,as_of:asOf?new Date(asOf).toISOString():undefined})}>Evaluate / replay</button><button className="text-button" onClick={()=>{setMemo(m.id);setSupersedes(c.id);setPredicate(c.predicate_json);setReason('')}}>Append justified change</button></div>})}<details><summary>Complete criterion and evaluation history</summary>{data.criteria.filter((c:any)=>c.memo_id===m.id).map((c:any)=><div key={c.id}><p>{when(c.known_from)} · {c.predicate_json}</p>{c.supersedes_id&&<p>Supersedes {c.supersedes_id}: {c.supersede_reason}</p>}{data.evaluations.filter((e:any)=>e.kill_criterion_id===c.id).map((e:any)=><div className={'criterion-card '+e.result} key={e.id}><strong>{e.result.toUpperCase()}</strong><p>Recorded {when(e.evaluated_at)} · As of {when(e.as_of)}</p><p className="preserve-text">{e.reason}</p>{e.supersedes_id&&<p>Supersedes evaluation {e.supersedes_id}. Original trip retained.</p>}<details><summary>Input records and evaluated snapshot</summary><pre>{JSON.stringify(JSON.parse(e.snapshot_json),null,2)}</pre></details></div>)}</div>)}</details></article>)}
 </>}
 {error&&<div className="feed-warning" role="alert">{error}</div>}
 <div className="section-heading"><div><h3>Recorded thesis alerts</h3><p>In-app records only. No phone notification or background monitoring is active.</p></div><button className="outline-button" disabled={busy} onClick={()=>void load()}>Refresh records</button></div>{(data?.alerts||[]).map((a:any)=>{const b=JSON.parse(a.body);return <article className={'criterion-card '+(a.tier==='Immediate'?'trip':'unknown')} key={a.id}><span className="badge">{a.tier}</span><h3>{b.title} — {b.company}</h3><p>Recorded {when(a.known_from)} · Condition defined {when(b.criterionCreatedAt)}</p><p className="preserve-text">{b.reason}</p><p>Your thesis assumed: {b.thesis}</p>{b.evidence.map((e:any,i:number)=><div key={i}><p>Current value: {e.current??'unknown'} · Period {e.periodEnd||'unknown'} · Streak {e.streak} of {e.condition.consecutive_periods||1}</p>{e.source&&<p>Source: {e.source.form} · {e.source.accession} · Filed {e.source.filed_at} · <a href={'https://www.sec.gov/Archives/edgar/data/'+Number(e.source.entity_id.split(':')[1])+'/'+e.source.accession.replaceAll('-','')+'/'+e.source.accession+'-index.html'} target="_blank" rel="noreferrer">SEC filing</a></p>}</div>)}<p>{b.note}</p></article>})}{data&&!data.alerts.length&&<p>No criterion alerts recorded. This does not establish that your investments are safe.</p>}</section>;
}
