"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {Radio,RefreshCw,ExternalLink,Clock,ShieldCheck,Newspaper} from "lucide-react";
import {Switch} from "@/components/ui/switch";
import type {NewsPayload,MarketPayload,NewsItem} from "@/lib/sentinel/feeds";
const date=(v:string|null)=>v?new Date(v).toLocaleString(undefined,{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit",timeZoneName:"short"}):"Publication time unavailable";
async function retryRead(url:string,signal:AbortSignal){for(let n=0;n<3;n++){try{const r=await fetch(url,{cache:'no-store',signal});if(r.ok||r.status<500)return r;}catch(e){if(signal.aborted)throw e;}if(n<2)await new Promise(r=>setTimeout(r,[400,1200][n]*(0.75+Math.random()/2)));}throw new Error('Stored feed unavailable');}
export function LiveDesk(){
 const [news,setNews]=useState<NewsPayload|null>(null),[market,setMarket]=useState<MarketPayload|null>(null),[errors,setErrors]=useState<Record<string,string>>({}),[busy,setBusy]=useState<Record<string,boolean>>({}),[auto,setAuto]=useState(true),[newCount,setNewCount]=useState(0),[now,setNow]=useState(Date.now()),[topic,setTopic]=useState("All updates"),[shown,setShown]=useState(12);
 const known=useRef<Set<string>|null>(null);const controllers=useRef<Record<string,AbortController>>({});const alive=useRef(true);
 const refresh=useCallback(async(kind:"news"|"market")=>{
  if(controllers.current[kind])return;const c=new AbortController();controllers.current[kind]=c;setBusy(b=>({...b,[kind]:true}));
  const timer=setTimeout(()=>c.abort(),30000);
  try{const r=await retryRead(`/api/${kind}`,c.signal);if(!r.ok)throw new Error("Response unavailable");const data=await r.json() as Record<string,unknown>;if(!alive.current)return;
   if(!Array.isArray(data.sources)||typeof data.checkedAt!=="string")throw new Error("Invalid response");
   if(kind==="news"){
    if(!Array.isArray(data.items))throw new Error("Invalid news");
    const next=data as unknown as NewsPayload;
    if(known.current){let count=0;for(const i of next.items){if(!known.current.has(i.id)&&i.publishedAt&&Date.now()-Date.parse(i.publishedAt)<86_400_000){count++;}known.current.add(i.id);}if(count)setNewCount(n=>n+count);}
    else if(next.sources.some(s=>s.status==="available"))known.current=new Set(next.items.map(i=>i.id));
    setNews(next);
   }else{if(!Array.isArray(data.quotes))throw new Error("Invalid prices");setMarket(data as unknown as MarketPayload);}
   setErrors(e=>({...e,[kind]:""}));
   await fetch("/api/refresh",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind}),signal:c.signal}).then(async r=>{if(!r.ok)throw new Error();const next=await r.json() as any;if(alive.current){if(kind==="market")setMarket(next);else setNews(next)}}).catch(()=>{if(alive.current)setErrors(e=>({...e,[kind]:"Source refresh failed; retained values may be stale."}))});
  }catch{if(alive.current)setErrors(e=>({...e,[kind]:"Refresh failed. Previously received information, if any, is not a current update."}));}
  finally{clearTimeout(timer);delete controllers.current[kind];if(alive.current)setBusy(b=>({...b,[kind]:false}));}
 },[]);
 useEffect(()=>{alive.current=true;void refresh("news");void refresh("market");const clock=setInterval(()=>setNow(Date.now()),10000);return()=>{alive.current=false;clearInterval(clock);Object.values(controllers.current).forEach(c=>c.abort());}},[refresh]);
 useEffect(()=>{if(!auto)return;const prices=setInterval(()=>{if(document.visibilityState==="visible")void refresh("market")},60000);const releases=setInterval(()=>{if(document.visibilityState==="visible")void refresh("news")},300000);const focus=()=>{if(document.visibilityState==="visible"){void refresh("market");void refresh("news")}};document.addEventListener("visibilitychange",focus);return()=>{clearInterval(prices);clearInterval(releases);document.removeEventListener("visibilitychange",focus)}},[auto,refresh]);
 const items=(news?.items||[]).filter(i=>topic==="All updates"||i.topic===topic);
 const feedFresh=!!news&&!errors.news&&now-Date.parse(news.checkedAt)<600000;
 const freshQuote=(receivedAt:string)=>!errors.market&&now-Date.parse(receivedAt)<120000;
 const sources=[...(news?.sources||[]),...(market?.sources||[])];
 return <section className="live-desk"><div className="section-heading"><div><div className="eyebrow lime">SOURCE-CONNECTED WORKSPACE</div><h2>Market & policy desk</h2><p>Official releases and indicative crypto prices. Coverage is limited.</p></div><button className="outline-button" disabled={busy.news||busy.market} onClick={()=>{void refresh("news");void refresh("market")}}><RefreshCw size={16} className={busy.news||busy.market?"spin":""}/>{busy.news||busy.market?"Checking sources…":"Refresh sources"}</button></div>
 <div className="live-settings"><label><Switch checked={auto} onCheckedChange={setAuto} aria-label="Refresh while this page is visible"/> Refresh while Market desk is visible</label><span>Crypto: 1 min · News: 5 min · Stops when closed</span></div>
 <div className="quote-grid">{[["BTC","Bitcoin"],["ETH","Ethereum"]].map(([symbol,name])=>{const q=market?.quotes.find(q=>q.symbol===symbol);return <div className="quote-card" key={symbol}><div><span className="asset-icon orange">{symbol==="BTC"?"₿":"Ξ"}</span><span>{name}<small>{symbol} / USD</small></span></div><strong>{q?new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(q.amount):busy.market?"Checking…":"Unavailable"}</strong><p>{q?`${!q.stale&&freshQuote(q.receivedAt)?"Received":"STALE · received"} ${date(q.receivedAt)} · ${Math.max(0,Math.floor((now-Date.parse(q.receivedAt))/60000))} min ago`:"No price has been received"}</p><small>Coinbase reference · Independent reconciliation unknown</small></div>})}<div className="quote-card muted-quote"><div><span className="asset-icon gold">Au</span><span>Gold & equities<small>Global coverage</small></span></div><strong>Provider required</strong><p>No stock or gold price feed connected.</p><small>Operating budget: $100–$200/month total</small></div></div>
 <p className="feed-footnote">Crypto prices have a retrieval time, not a provider trade timestamp. Single-source references are not verified execution prices. Failed feeds retain the last successful value, labelled stale.</p>
 {Object.entries(errors).filter(([,v])=>v).map(([k,v])=><div role="status" className="feed-warning" key={k}>{k==="news"?"News":"Prices"}: {v}</div>)}
 <div className="source-health">{sources.map(s=><span title={s.message} key={s.name} className={s.status==="available"?"source-ok":"source-error"}>{s.status==="available"?<ShieldCheck size={14}/>:<Clock size={14}/>} {s.name}: {s.status==="available"?"last fetch succeeded":s.status==="degraded"?"degraded · retry paused":"unavailable / stale"}</span>)}</div>
 {newCount>0&&<div role="status" className="new-releases"><Newspaper size={18}/>{newCount} newly detected release{newCount===1?"":"s"} published within the last 24 hours.<button className="text-button" onClick={()=>setNewCount(0)}>Dismiss</button></div>}
 <div className="news-heading"><h3>Latest {Math.min(shown,items.length)} of {items.length} retrieved</h3><span>{news?`${feedFresh?"Checked":"STALE · checked"} ${date(news.checkedAt)}`:"Waiting for source response"}</span></div>
 <p className="feed-footnote">Fed and ECB coverage only. Topic explanations below use headline keywords; they are not summaries of the full release or trading signals.</p>
 <div className="topic-buttons" role="group" aria-label="Filter official releases">{["All updates","Rates & inflation","Banks & stability","Digital assets","Trade & geopolitics"].map(t=><button key={t} className={topic===t?"active":""} aria-pressed={topic===t} onClick={()=>{setTopic(t);setShown(12)}}>{t}</button>)}</div>
 <div className="coverage-panel"><strong>{topic==="All updates"?"Connected coverage":topic+" coverage"}</strong><p>{topic==="Digital assets"||topic==="Trade & geopolitics"?"No dedicated source connected for this topic. Fed/ECB references are incidental; this is not a comprehensive policy or geopolitical feed.":"European Central Bank and Federal Reserve official feeds only. Company announcements and other jurisdictions are not covered."}</p><p>{(news?.items||[]).filter(i=>(topic==="All updates"||i.topic===topic)&&i.publishedAt&&now-Date.parse(i.publishedAt)<=30*86400000).length} retrieved items dated within 30 days · Feed window only, not a complete 30-day archive.</p></div>
 <div className="news-list">{items.slice(0,shown).map(i=><article className="news-row" key={i.id}><div className="news-meta"><span>{i.source}</span><time dateTime={i.publishedAt||undefined}>{date(i.publishedAt)}{i.publishedAt&&now-Date.parse(i.publishedAt)>86400000?" · Earlier release":""}</time></div><h3><a href={i.url} target="_blank" rel="noreferrer">{i.title}<ExternalLink size={15}/></a></h3><span className="badge">Tier 1 · {i.topic}</span><span className="badge">Policy status: unclassified</span>{i.stale&&<span className="badge">STALE SOURCE SNAPSHOT</span>}<p className="feed-footnote">Retrieved {date(i.receivedAt)}{i.knownFrom?" · Snapshot recorded "+date(i.knownFrom):""}</p><details><summary>General topic background — not analysis of this release</summary><div className="news-context"><strong>General topic context · Full release not analysed</strong><p>{i.context}</p><strong>What to check next</strong><p>{i.watch}</p><p className="feed-footnote">The source and headline are retrieved. Market impact, hidden intentions and price reaction have not been established.</p></div></details></article>)}</div>
 {items.length>shown&&<button className="outline-button" onClick={()=>setShown(n=>n+12)}>Show more · {Math.min(shown,items.length)} of {items.length} shown</button>}
 {!items.length&&<div className="empty"><Radio size={28}/><h3>{busy.news?"Reading official sources…":topic==="Digital assets"||topic==="Trade & geopolitics"?"No dedicated topic source connected":news?.items.length?"No matching items in the retrieved feed window":"No releases available"}</h3><p>{news?.items.length?"This is limited source coverage, not evidence that nothing happened.":"Unavailable sources stay visible above. No sample headlines will be inserted here."}</p></div>}
 <div className="feed-footnote reference-links">Feed documentation: <a href="https://www.ecb.europa.eu/home/html/rss.en.html" target="_blank" rel="noreferrer">ECB</a> · <a href="https://www.federalreserve.gov/feeds/feeds.htm" target="_blank" rel="noreferrer">Federal Reserve</a> · <a href="https://docs.cdp.coinbase.com/coinbase-business/track-apis/prices" target="_blank" rel="noreferrer">Coinbase</a></div>
 </section>
}
