"use client";
import {newId} from '@/lib/sentinel/client-id';
import {useEffect,useState,useRef} from 'react';
import {BookOpen,Plus,ShieldCheck,History,ExternalLink} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {WorkspaceData} from '@/lib/sentinel/contracts';
const when=(v:string)=>new Date(v).toLocaleString();
export function Instruments({items,onChange}:{items:WorkspaceData['instruments'];onChange:(items:WorkspaceData['instruments'])=>void}){
 const [identifier,setIdentifier]=useState(''),[name,setName]=useState(''),[exchange,setExchange]=useState(''),[kind,setKind]=useState('Stock'),[error,setError]=useState('');
 const add=()=>{if(!identifier.trim()||!name.trim()||(kind==='Stock'&&!exchange.trim())){setError('Enter a name, identifier and, for stocks, an exchange or jurisdiction.');return}if(items.length>=200){setError('The watchlist limit is 200 entities.');return}const id=newId();onChange([...items,{id,identifier:identifier.trim().toUpperCase(),exchange:exchange.trim(),name:name.trim(),kind:kind as 'Stock'|'Gold'|'Crypto',availability:'unconfirmed',availabilityEvidence:'',resolution:'unverified'}]);setIdentifier('');setName('');setExchange('');setError('');};
 return <section className="record-panel"><h3>Your research entities</h3><p>Add any company or asset. Identifiers are recorded as entered, not resolved or verified against a provider. Each receives a stable internal ID.</p><div className="entity-form"><label>Name<input maxLength={120} value={name} onChange={e=>setName(e.target.value)} placeholder="Company or asset name"/></label><label>Ticker, CIK or ISIN<input maxLength={80} value={identifier} onChange={e=>setIdentifier(e.target.value)} placeholder="ASML / CIK… / ISIN…"/></label><label>Exchange / jurisdiction<input maxLength={80} value={exchange} onChange={e=>setExchange(e.target.value)} placeholder="Amsterdam"/></label><label>Asset class<Select value={kind} onValueChange={setKind}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['Stock','Gold','Crypto'].map(v=><SelectItem value={v} key={v}>{v}</SelectItem>)}</SelectContent></Select></label><button className="primary-button" onClick={add}><Plus size={16}/>Add entity</button></div>{error&&<p role="alert" className="red-text">{error}</p>}
 <div className="entity-list">{items.map(i=><article key={i.id}><div><strong>{i.name}</strong><p>{i.identifier} · {i.exchange||'No exchange specified'} · {i.kind}</p><span className="badge">Identity unverified</span>{i.kind==='Crypto'&&<span className="badge">Speculative research · fraud checks unknown</span>}</div><div><label>Revolut availability<Select value={i.availability} onValueChange={v=>{if(v==='confirmed'&&i.availabilityEvidence.trim().length<5){setError('Record how you checked availability before marking it confirmed.');return}setError('');onChange(items.map(x=>x.id===i.id?{...x,availability:v as typeof i.availability}:x))}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="unconfirmed">Unconfirmed</SelectItem><SelectItem value="confirmed">Confirmed by you</SelectItem><SelectItem value="no">Not available</SelectItem></SelectContent></Select></label><label>Verification note<input maxLength={1500} value={i.availabilityEvidence} onChange={e=>onChange(items.map(x=>x.id===i.id?{...x,availabilityEvidence:e.target.value,availability:x.availability==='confirmed'&&e.target.value.trim().length<5?'unconfirmed':x.availability}:x))} placeholder="Listing, account check date and evidence"/></label><button className="text-button" onClick={()=>onChange(items.filter(x=>x.id!==i.id))}>Remove from current watchlist</button></div></article>)}</div></section>
}
export function Journal(){
 const lastAttempt=useRef<{id:string;fingerprint:string}|null>(null);
 const [entries,setEntries]=useState<any[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[cursor,setCursor]=useState<string|null>(null);
 const [kind,setKind]=useState('thesis'),[entity,setEntity]=useState(''),[statement,setStatement]=useState(''),[counter,setCounter]=useState(''),[references,setReferences]=useState(''),[disposition,setDisposition]=useState('research'),[probability,setProbability]=useState(''),[due,setDue]=useState(''),[rule,setRule]=useState(''),[requestId,setRequestId]=useState(''),[resolution,setResolution]=useState<any>(null),[outcome,setOutcome]=useState('1'),[evidence,setEvidence]=useState(''),[sourceUrl,setSourceUrl]=useState('');
 async function load(more=false){try{setLoading(true);const r=await fetch('/api/journal'+(more&&cursor?'?before='+encodeURIComponent(cursor):''),{cache:'no-store'});const j=await r.json() as any;if(!r.ok)throw new Error(j.error);setEntries(old=>more?[...old,...j.entries]:j.entries);setCursor(j.nextCursor);setError('');}catch(e){setError(e instanceof Error?e.message:'Journal unavailable')}finally{setLoading(false)}}
 useEffect(()=>{void load();setRequestId(newId())},[]);
 useEffect(()=>{const prevent=(e:BeforeUnloadEvent)=>{if(statement||counter||references){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',prevent);return()=>window.removeEventListener('beforeunload',prevent)},[statement,counter,references]);
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);try{const parsed=kind==='prediction'&&probability!==''?Number(probability)/100:null;const date=kind==='prediction'&&due?new Date(due).toISOString():null;const fingerprint=JSON.stringify({kind,entity,statement,counter,references,disposition,parsed,date,rule});const entryId=lastAttempt.current?.fingerprint===fingerprint?lastAttempt.current.id:newId();lastAttempt.current={id:entryId,fingerprint};const r=await fetch('/api/journal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:entryId,kind,entity,statement,counterEvidence:counter,references,disposition,probability:parsed,resolvesAt:date,resolutionRule:kind==='prediction'?rule:''})});const j=await r.json() as any;if(!r.ok)throw new Error(j.error);lastAttempt.current=null;setStatement('');setCounter('');setReferences('');setProbability('');setDue('');setRule('');setRequestId(newId());await load()}catch(e){setError(e instanceof Error?e.message:'Entry not recorded')}finally{setBusy(false)}}
 async function resolve(){setBusy(true);try{const r=await fetch('/api/journal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:"resolution",requestId:requestId,resolves_id:resolution.id,outcome:Number(outcome),evidence,resolution_source_url:sourceUrl,supersedes_id:resolution.resolution_id||null})});const j=await r.json() as any;if(!r.ok)throw new Error(j.error);setResolution(null);setEvidence('');setSourceUrl('');setRequestId(newId());await load()}catch(e){setError(e instanceof Error?e.message:'Resolution failed')}finally{setBusy(false)}}
 return <section><div className="section-heading"><div><h2>Research journal</h2><p>Write before the outcome. Submitted entries and resolutions cannot be edited or deleted.</p></div><BookOpen size={22}/></div><div className="feed-warning">This is a research record, not trade approval. Memo gates, portfolio limits and cooling-off enforcement are not yet implemented.</div>
 <form onSubmit={create} className="record-panel"><div className="entity-form"><label>Record type<Select value={kind} onValueChange={setKind}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['thesis','prediction','decision'].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></label><label>Company / asset<input required maxLength={120} value={entity} onChange={e=>setEntity(e.target.value)}/></label><label>Conclusion<Select value={disposition} onValueChange={setDisposition}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="research">Continue research</SelectItem><SelectItem value="wait">Wait</SelectItem><SelectItem value="already-moved">Already moved — user judgment</SelectItem><SelectItem value="unknowable">Unknowable</SelectItem></SelectContent></Select></label></div><label>Statement and reasoning<textarea required minLength={20} maxLength={12000} value={statement} onChange={e=>setStatement(e.target.value)} placeholder="State exactly what you believe and why."/></label><label>What would prove this wrong?<textarea required minLength={10} maxLength={12000} value={counter} onChange={e=>setCounter(e.target.value)} placeholder="Specific disconfirming evidence or conditions."/></label><label>Sources and evidence<textarea maxLength={6000} value={references} onChange={e=>setReferences(e.target.value)} placeholder="Links, filing dates, page numbers and observations. User-entered; not independently verified."/></label>
 {kind==='prediction'&&<div className="prediction-fields"><div className="entity-form"><label>Your probability (%)<input type="number" min="0" max="100" step="0.1" required value={probability} onChange={e=>setProbability(e.target.value)}/></label><label>Resolution date (your local time)<input type="datetime-local" required value={due} onChange={e=>setDue(e.target.value)}/></label></div><label>Objective resolution rule<textarea required minLength={10} maxLength={4000} value={rule} onChange={e=>setRule(e.target.value)} placeholder="What measurable outcome and source will resolve this as true or false?"/></label><p className="feed-footnote">The probability is your estimate, not a model forecast. Brier score is calculated only after you record an outcome.</p></div>}
 <button className="primary-button" disabled={busy||!requestId}><ShieldCheck size={16}/>{busy?'Recording…':'Record permanently'}</button></form>
 {error&&<div className="feed-warning" role="alert">{error}<button className="text-button" onClick={()=>void load()}>Reload records</button></div>}
 <div className="journal-list">{entries.map(e=><article key={e.id} className="record-panel"><div className="news-meta"><span>{e.kind} · {e.entity||'Browser-state migration'}</span><time>{when(e.created_at)}</time></div>{e.kind==='legacy_import'?<p>Existing browser research was imported at this time. Its earlier creation dates are unknown; original content is retained in the audit record.</p>:<><h3>{e.body.disposition==='already-moved'?'Already moved — user judgment':e.body.disposition}</h3><p className="preserve-text">{e.body.statement}</p><details><summary>Counter-evidence and references</summary><p className="preserve-text">{e.body.counterEvidence}</p><p className="preserve-text">{e.body.references||'No references recorded'}</p></details>{e.kind==='prediction'&&<div className="prediction-result"><p>Your estimate: {(e.probability*100).toFixed(1)}% · Resolves {when(e.resolves_at)}</p><p>{e.body.resolutionRule}</p>{e.outcome===null?<><span className="badge amber-text">{Date.parse(e.resolves_at)<=Date.now()?"Overdue — unresolved":"Unresolved"}</span>{Date.parse(e.resolves_at)<=Date.now()&&<button className="outline-button" onClick={()=>{setResolution(e);setEvidence('')}}>Record outcome</button>}</>:<><p>Outcome: {e.outcome===1?'True':'False'} · Brier score: {((e.probability-e.outcome)**2).toFixed(4)} (lower is better)</p><p>Resolved {when(e.resolved_at)} · User-assessed outcome</p><p className="preserve-text">{e.evidence}</p><button className="outline-button" onClick={()=>{setResolution(e);setEvidence('');setSourceUrl('');setRequestId(newId())}}>Append correction</button><details><summary>Resolution history ({e.resolutionHistory?.length||0})</summary>{e.resolutionHistory?.map((r:any)=><p key={r.id}>{when(r.resolved_at)} · Outcome {r.outcome} · {r.evidence} {r.source_url&&<a href={r.source_url} target="_blank" rel="noreferrer">Source</a>}{r.supersedes_id?" · Supersedes "+r.supersedes_id:""}</p>)}</details></>}</div>}</>}</article>)}</div>
 {!entries.length&&!loading&&<div className="empty"><History/><h3>No records yet</h3><p>Start with a falsifiable statement or a reason to wait.</p></div>}{loading&&<p>Loading records…</p>}{cursor&&<button className="outline-button" disabled={loading} onClick={()=>void load(true)}>Load earlier records</button>}
 <Dialog open={!!resolution} onOpenChange={o=>{if(!o)setResolution(null)}}><DialogContent><DialogHeader><DialogTitle>Resolve this prediction</DialogTitle><DialogDescription>This resolution is permanent. Use the original rule and cite supporting evidence.</DialogDescription></DialogHeader><Select value={outcome} onValueChange={setOutcome}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="1">True — outcome occurred</SelectItem><SelectItem value="0">False — outcome did not occur</SelectItem></SelectContent></Select><label>Evidence<textarea minLength={20} value={evidence} onChange={e=>setEvidence(e.target.value)}/></label><label>Resolution source URL<input type="url" value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} placeholder="https://…"/></label>{error&&<p role="alert">{error}</p>}<button className="primary-button" disabled={busy||evidence.trim().length<20||!sourceUrl.startsWith("https://")} onClick={resolve}>Record permanent resolution</button></DialogContent></Dialog></section>
}
export function DataHistory(){
 const [at,setAt]=useState(''),[data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[capture,setCapture]=useState<any>(null);
 async function load(){setBusy(true);try{const query=at?'?asOf='+encodeURIComponent(new Date(at).toISOString()):'';const r=await fetch('/api/history'+query,{cache:'no-store'});const j=await r.json() as any;if(!r.ok)throw new Error(j.error);setData(j);setError('')}catch(e){setError(e instanceof Error?e.message:'History unavailable')}finally{setBusy(false)}}
 async function raw(id:string){try{const r=await fetch('/api/history?raw='+encodeURIComponent(id));const j=await r.json() as any;if(!r.ok)throw new Error(j.error);setCapture(j)}catch(e){setError(e instanceof Error?e.message:'Capture unavailable')}}
 useEffect(()=>{void load()},[]);
 return <section><div className="section-heading"><div><h2>What did we know?</h2><p>Server-recorded source history. No information is backdated.</p></div></div><div className="entity-form record-panel"><label>As of (your local time)<input type="datetime-local" value={at} onChange={e=>setAt(e.target.value)}/></label><button className="primary-button" disabled={busy} onClick={load}>{busy?'Loading…':'Inspect recorded history'}</button></div>{error&&<p className="feed-warning" role="alert">{error}</p>}{data&&<><p className="feed-footnote">{data.notice}</p><p className="feed-footnote">Recording began: {data.recordingStarted?when(data.recordingStarted):'No successful capture yet'} · Cutoff: {when(data.asOf)}</p><div className="record-panel"><h3>Source state at the cutoff</h3>{data.sources.length?data.sources.map((s:any)=><p key={s.source}>{s.source}: {s.status} · {when(s.completedAt)} · {s.attempts} attempt(s){s.error?' · '+s.error:''}</p>):<p>No collection attempts recorded by this time.</p>}</div><div className="record-panel"><h3>Last recorded price references</h3>{data.quotes.length?data.quotes.map((q:any)=><div className="history-row" key={q.symbol}><p>{q.symbol}: {q.amount} {q.currency} · Retrieved {when(q.receivedAt)}<br/><small>Historical snapshot · Source trade time unavailable · Independent reconciliation unknown</small></p><button className="text-button" onClick={()=>void raw(q.rawEventId)}>Inspect original response</button></div>):<p>No prices known at this time.</p>}</div><div className="record-panel"><h3>Releases known at the cutoff ({data.news.length})</h3>{data.news.map((n:any)=><div className="history-row" key={n.id}><div><a href={n.url} target="_blank" rel="noreferrer">{n.title} <ExternalLink size={13}/></a><p className="feed-footnote">Published: {n.publishedAt?when(n.publishedAt):'Unknown'} · Snapshot recorded: {when(n.knownFrom)}</p></div><button className="text-button" onClick={()=>void raw(n.rawEventId)}>Inspect capture</button></div>)}</div><div className="record-panel"><h3>Operational incidents</h3><p className="feed-footnote">These are feed-health records, not market alerts. No scheduled-run monitoring exists yet.</p>{data.health.length?data.health.map((h:any)=><p key={h.id}>{when(h.created_at)} · {h.entity} · {h.body.message}</p>):<p>No recorded three-failure incidents by this cutoff.</p>}</div></>}
 <Dialog open={!!capture} onOpenChange={o=>{if(!o)setCapture(null)}}><DialogContent className="raw-dialog"><DialogHeader><DialogTitle>Original source capture</DialogTitle><DialogDescription>Immutable, decoded HTTP response. Source timestamps are not inferred.</DialogDescription></DialogHeader>{capture&&<><p>{capture.source} · Retrieved {when(capture.fetched_at)}</p><p className="feed-footnote">SHA-256: {capture.content_hash}</p><pre>{capture.payload}</pre></>}</DialogContent></Dialog></section>
}
